[package]
name = "protocol-support"
version = "0.1.0"
edition = "2024"

[dependencies]
cpu-time = { workspace = true }
rayon = { workspace = true }
crypto-primitives = { path = "../../crypto-primitives" }
postcard = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
