//! Observation boundary: protocol driving emits events; the caller owns artifact I/O.
use serde::{Deserialize, Serialize};
pub const NODE_LOG_SCHEMA: &str = "silk-node-log/v5";
pub const WIRE_ACCOUNTING_MODE: &str = "sender-side-framed-node-request/v1";
pub const TRANSPORT_PROFILE: &str = "persistent-peer-tcp";

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NodeEvent {
    pub schema_version: String,
    pub node_sequence: u64,
    pub event_kind: String,
    pub run_id: String,
    pub experiment_id: String,
    pub sample_id: String,
    pub sample_role: String,
    pub implementation: String,
    pub implementation_profile: String,
    pub protocol_revision: String,
    pub build_git_commit: String,
    pub build_source_fingerprint: String,
    pub node_id: u32,
    pub role: String,
    pub n: u32,
    pub t: u32,
    pub epoch_slots: u32,
    pub seed: u64,
    pub executor: String,
    pub network_scenario: String,
    pub resource_profile: String,
    pub clock_source: String,
    pub wire_accounting_mode: String,
    pub transport_profile: String,
    pub sample: u32,
    pub epoch: Option<u64>,
    pub slot: Option<u32>,
    pub output_kind: Option<String>,
    pub phase: String,
    pub headline_phase: String,
    pub relative_start_ns: u64,
    pub relative_end_ns: u64,
    pub monotonic_start_ns: u64,
    pub monotonic_end_ns: u64,
    pub unix_start_ns: u64,
    pub unix_end_ns: u64,
    pub wall_ns: u64,
    pub process_cpu_ns: u64,
    pub cpu_ns: u64,
    pub receive_deserialize_cpu_ns: u64,
    pub bytes_sent: u64,
    pub bytes_received: u64,
    pub actual_wire_bytes: u64,
    pub protocol_wire_bytes_sent: u64,
    pub protocol_wire_bytes_received: u64,
    pub messages_sent: u64,
    pub messages_received: u64,
    pub rss_peak_bytes: u64,
    pub protocol_storage_bytes: u64,
    pub actual_reconstruction_backend: String,
    pub certificate_encoding: String,
    pub gc_mode: String,
    pub gc_before_bytes: Option<u64>,
    pub gc_after_bytes: Option<u64>,
    pub gc_reclaimed_bytes: Option<u64>,
    pub gc_discarded_objects: Option<u64>,
    pub gc_persistent_before_bytes: Option<u64>,
    pub gc_persistent_after_bytes: Option<u64>,
    pub gc_persistent_bytes_written: Option<u64>,
    pub gc_retained_due_to_service_window_bytes: Option<u64>,
    pub output_digest: Option<[u8; 32]>,
    pub success: bool,
    pub status: String,
    pub error_class: Option<String>,
    pub rondo_breeze_fidelity: String,
    pub rondo_bft_path_fidelity: String,
    pub rondo_breeze_profile: String,
    pub rondo_bft_profile: String,
    pub rondo_bft_signature_profile: String,
    pub spurt_fidelity: String,
    pub coverage: String,
    pub claim_scope: String,
    pub host_id: String,
    pub container_id: Option<String>,
}

pub trait NodeObserver {
    fn record(&mut self, event: &NodeEvent) -> std::io::Result<()>;
    fn artifact(&mut self, name: &str, bytes: &[u8]) -> std::io::Result<()>;
    fn finish(&mut self) -> std::io::Result<String>;
}
