[package]
name = "experiment-runner"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
beacon-node = { path = "../../beacon-node" }
experiment-records = { path = "../records" }
clap = { workspace = true }
crypto-primitives = { path = "../../crypto-primitives" }
curve25519-dalek = { workspace = true }
hex = { workspace = true }
protocol-support = { path = "../protocol" }
rand = { workspace = true }
rand_chacha = { workspace = true }
rondo-bavss-po = { path = "../../rondo-bavss-po" }
serde = { workspace = true }
serde_json = { workspace = true }
silk-bavss-po = { path = "../../silk-bavss-po" }
thiserror = { workspace = true }
toml = { workspace = true }

[build-dependencies]
crypto-primitives = { path = "../../crypto-primitives" }
hex = { workspace = true }
