use crate::BreezeError;
use crate::primitives::merkle::{MerkleTree, commitment_leaf};
use crate::primitives::poly_commit::PolyCommitment;
use crate::protocol::breeze_verify::{batch_challenges, gamma_digest};
use crate::protocol::types::{
    BatchEvaluationProof, BreezePublicData, BreezeRowData, ProtocolParams,
};
use crypto_primitives::hash::HashTranscript;
use crypto_primitives::polynomial::{evaluate, random_scalar, sample_polynomial};
use curve25519_dalek::ristretto::RistrettoPoint;
use curve25519_dalek::scalar::Scalar;
use rand::RngCore;

#[derive(Clone, Debug)]
struct DealerState {
    polynomials: Vec<Vec<Scalar>>,
    commitments: Vec<RistrettoPoint>,
    mask_polynomial: Vec<Scalar>,
    mask_commitment: RistrettoPoint,
}

#[derive(Clone, Debug)]
pub struct BreezeDealer {
    sid: Vec<u8>,
    dealer_id: usize,
    secrets: Vec<Scalar>,
    params: ProtocolParams,
    poly_commit: PolyCommitment,
    state: Option<DealerState>,
}

impl BreezeDealer {
    pub fn new(
        dealer_id: usize,
        secrets: Vec<Scalar>,
        params: ProtocolParams,
    ) -> Result<Self, BreezeError> {
        params.validate()?;
        if dealer_id >= params.n {
            return Err(BreezeError::InvalidDealer);
        }
        if secrets.len() != params.l {
            return Err(BreezeError::InvalidShareCount {
                got: secrets.len(),
                expected: params.l,
            });
        }
        Ok(Self {
            sid: b"rondo-breeze".to_vec(),
            dealer_id,
            secrets,
            params,
            poly_commit: PolyCommitment::new(params.d)?,
            state: None,
        })
    }

    pub fn random<R: RngCore + ?Sized>(
        dealer_id: usize,
        params: ProtocolParams,
        rng: &mut R,
    ) -> Result<Self, BreezeError> {
        let secrets = (0..params.l).map(|_| random_scalar(rng)).collect();
        Self::new(dealer_id, secrets, params)
    }

    /// Breeze BatchCommit plus evaluation of every committed polynomial for
    /// every receiver. BatchEval proofs are generated by `batch_eval`;
    /// callers choose the measurement boundary that includes that work.
    pub fn share<R: RngCore + ?Sized>(
        &mut self,
        rng: &mut R,
    ) -> Result<(BreezePublicData, Vec<BreezeRowData>), BreezeError> {
        let polynomials = self
            .secrets
            .iter()
            .copied()
            .map(|secret| sample_polynomial(secret, self.params.d, rng))
            .collect::<Result<Vec<_>, _>>()?;
        let public_commitments = self.poly_commit.batch_commit(&polynomials)?;
        let tree = commitment_tree(&public_commitments)?;
        let rows = (0..self.params.n)
            .map(|receiver_id| {
                let eval_point = Scalar::from(receiver_id as u64 + 1);
                BreezeRowData {
                    dealer_id: self.dealer_id,
                    receiver_id,
                    shares: polynomials
                        .iter()
                        .map(|poly| evaluate(poly, eval_point))
                        .collect(),
                    eval_point,
                }
            })
            .collect::<Vec<_>>();
        let mask_polynomial = (0..self.params.d)
            .map(|_| random_scalar(rng))
            .collect::<Vec<_>>();
        let mask_commitment = self.poly_commit.commit(&mask_polynomial)?;
        let mask_evaluations = rows
            .iter()
            .map(|row| evaluate(&mask_polynomial, row.eval_point))
            .collect::<Vec<_>>();
        let evaluations = evaluation_tree(&rows, &mask_evaluations)?;
        let public = BreezePublicData {
            sid: self.sid.clone(),
            dealer_id: self.dealer_id,
            params: self.params,
            commitments: public_commitments.clone(),
            commitment_root: tree.root(),
            evaluation_root: evaluations.root(),
            mask_commitment,
        };
        self.state = Some(DealerState {
            polynomials,
            commitments: public_commitments,
            mask_polynomial,
            mask_commitment,
        });
        Ok((public, rows))
    }

    /// Breeze BatchEval from Fig. 7. It creates one evaluation-bound aggregate
    /// polynomial proof member for every receiver.
    pub fn batch_eval(
        &self,
        public: &BreezePublicData,
        rows: &[BreezeRowData],
    ) -> Result<Vec<BatchEvaluationProof>, BreezeError> {
        if rows.len() != self.params.n {
            return Err(BreezeError::InvalidShareCount {
                got: rows.len(),
                expected: self.params.n,
            });
        }
        for (receiver, row) in rows.iter().enumerate() {
            self.check_row(public, row)?;
            if row.receiver_id != receiver {
                return Err(BreezeError::InvalidReceiver);
            }
        }
        let state = self.state.as_ref().ok_or(BreezeError::MissingDealerState)?;
        let eval_points = rows.iter().map(|row| row.eval_point).collect::<Vec<_>>();
        let mask_evaluations = eval_points
            .iter()
            .map(|point| evaluate(&state.mask_polynomial, *point))
            .collect::<Vec<_>>();
        let evaluations = evaluation_tree(rows, &mask_evaluations)?;
        if public.commitments != state.commitments
            || public.mask_commitment != state.mask_commitment
            || public.evaluation_root != evaluations.root()
        {
            return Err(BreezeError::InvalidBatchProof);
        }
        let gammas = batch_challenges(public)?;
        let mut aggregate_coefficients = vec![Scalar::ZERO; self.params.d];
        let mut aggregate_commitment = state.mask_commitment;
        for (index, gamma) in gammas.iter().copied().enumerate() {
            for (target, coefficient) in aggregate_coefficients
                .iter_mut()
                .zip(state.polynomials[index].iter())
            {
                *target += gamma * coefficient;
            }
            aggregate_commitment += gamma * state.commitments[index];
        }
        for (target, mask) in aggregate_coefficients
            .iter_mut()
            .zip(state.mask_polynomial.iter())
        {
            *target += mask;
        }
        let aggregate_shares = rows
            .iter()
            .zip(mask_evaluations.iter())
            .map(|(row, mask)| {
                row.shares
                    .iter()
                    .zip(gammas.iter())
                    .fold(*mask, |sum, (share, gamma)| sum + gamma * share)
            })
            .collect::<Vec<_>>();
        let proof_vector = self.poly_commit.batch_eval(
            aggregate_commitment,
            &aggregate_coefficients,
            &eval_points,
            &aggregate_shares,
        )?;
        (0..self.params.n)
            .map(|receiver_id| {
                Ok(BatchEvaluationProof {
                    dealer_id: self.dealer_id,
                    receiver_id,
                    commitment_root: public.commitment_root,
                    evaluation_root: public.evaluation_root,
                    gamma_digest: gamma_digest(&gammas),
                    mask_commitment: state.mask_commitment,
                    mask_evaluation: mask_evaluations[receiver_id],
                    evaluation_proof: evaluations.proof(receiver_id)?,
                    proof_member: proof_vector[receiver_id].clone(),
                })
            })
            .collect()
    }

    fn check_row(&self, public: &BreezePublicData, row: &BreezeRowData) -> Result<(), BreezeError> {
        if public.dealer_id != self.dealer_id || row.dealer_id != self.dealer_id {
            return Err(BreezeError::InvalidDealer);
        }
        if public.params != self.params {
            return Err(BreezeError::InvalidParameters);
        }
        if row.receiver_id >= self.params.n {
            return Err(BreezeError::InvalidReceiver);
        }
        if row.shares.len() != self.params.l {
            return Err(BreezeError::InvalidShareCount {
                got: row.shares.len(),
                expected: self.params.l,
            });
        }
        Ok(())
    }
}

pub(crate) fn commitment_tree(commitments: &[RistrettoPoint]) -> Result<MerkleTree, BreezeError> {
    MerkleTree::new(
        commitments
            .iter()
            .enumerate()
            .map(|(index, point)| commitment_leaf(index, &point.compress().to_bytes()))
            .collect(),
    )
}

pub(crate) fn evaluation_tree(
    rows: &[BreezeRowData],
    mask_evaluations: &[Scalar],
) -> Result<MerkleTree, BreezeError> {
    if rows.len() != mask_evaluations.len() {
        return Err(BreezeError::InvalidShareCount {
            got: mask_evaluations.len(),
            expected: rows.len(),
        });
    }
    MerkleTree::new(
        rows.iter()
            .zip(mask_evaluations)
            .map(|(row, mask_evaluation)| evaluation_leaf(row, *mask_evaluation))
            .collect(),
    )
}

pub(crate) fn evaluation_leaf(row: &BreezeRowData, mask_evaluation: Scalar) -> [u8; 32] {
    let mut hasher = HashTranscript::new(b"Rondo-Breeze-evaluation-leaf-v1");
    hasher.update(&(row.dealer_id as u64).to_le_bytes());
    hasher.update(&(row.receiver_id as u64).to_le_bytes());
    hasher.update(&row.eval_point.to_bytes());
    hasher.update(&(row.shares.len() as u64).to_le_bytes());
    for share in &row.shares {
        hasher.update(&share.to_bytes());
    }
    hasher.update(&mask_evaluation.to_bytes());
    hasher.finalize()
}
