[package]
name = "rondo-beacon"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-primitives = { path = "../crypto-primitives" }
curve25519-dalek = { workspace = true }
protocol-support = { path = "../support/protocol" }
rand = { workspace = true }
rand_chacha = { workspace = true }
rondo-bavss-po = { path = "../rondo-bavss-po" }
serde = { workspace = true }
thiserror = { workspace = true }
